### ISSUE TITLE
class ClientTEST

### ISSUE THREAD

**Issue by ACM-Unit** [toadkick/SeaBattle#11]
Класс ClientTEST, по названию похоже, что к функционалу приложения не имеет никакого отношения. Если так, то удалите его.
Для оформления тестов нужно было использовать одну из библиотек, к примеру junit, тогда бы это имело смысл. Каждый раз при сборке jar, ваше приложение проходило бы тесты

**Comment by zriv3** [comment]
удалил

**Comment by zriv3** [comment]
https://github.com/toadkick/SeaBattle/commit/97692d96e76aed677b8c14cdf19dc923f343a078
