### ISSUE TITLE
equals & hashcode

### ISSUE THREAD

**Issue by ACM-Unit** [toadkick/SeaBattle#2]
При использовании HashSet желательно переопределить equals и hashcode в классе объектов которые хранятся в этой коллекции.

**Comment by zriv3** [comment]
у PlayerController теперь equals() и hashCode() переопределены

**Comment by zriv3** [comment]
https://github.com/toadkick/SeaBattle/commit/f8fdb8bf5730406e6ec3f04092ea5b8ba9fe4a0c
