### ISSUE TITLE
admin functional

### ISSUE THREAD

**Issue by ACM-Unit** [toadkick/SeaBattle#21]
При логине с ролью админа не нашел возможности банить игроков и ip адресса(Хотя в коде видел такой функционал). Также у администратора должна быть возможность перезагрузки сервера и остановки сервера.

**Comment by CDP1988** [comment]
Added buttons for admin in client

**Comment by zriv3** [comment]
https://github.com/toadkick/SeaBattle/commit/3ce33c5f1381a7a145e93c823a0a9ba475ca76f7
