### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by ACM-Unit** [toadkick/SeaBattle#8]
Закомментированные строчки кода нужно убрать

**Comment by CDP1988** [comment]
commented lines of code removed

**Comment by perceptib2e** [comment]
и коммит Дмитрия https://github.com/toadkick/SeaBattle/commit/3abdb1e4e1e37358f27cf030caae3d640ddb9f6a

**Comment by zriv3** [comment]
1. https://github.com/toadkick/SeaBattle/commit/3abdb1e4e1e37358f27cf030caae3d640ddb9f6a
2. https://github.com/toadkick/SeaBattle/commit/7f08f29e044e2f7bec7a0e2b417eaec34d89565a
