### ISSUE TITLE
javadocs instead of comments

### ISSUE THREAD

**Issue by ACM-Unit** [toadkick/SeaBattle#9]
При описании методов используйте javadocs, а не обычные комментарии

**Comment by zriv3** [comment]
https://github.com/toadkick/SeaBattle/commit/f8fdb8bf5730406e6ec3f04092ea5b8ba9fe4a0c
https://github.com/toadkick/SeaBattle/commit/3ce33c5f1381a7a145e93c823a0a9ba475ca76f7
https://github.com/toadkick/SeaBattle/commit/7f08f29e044e2f7bec7a0e2b417eaec34d89565a
